blog/urls.py
# encoding: utf-8
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url # Django < 1.6

from blog.models import Post, Blog
from blog import settings


urlpatterns = patterns('blog.views',
    url(r'^$', 'post_list', name='blog_post_list'),
    url(r'^my_posts/$', 'my_post_list', name='blog_my_post_list'),
    url(r'^add/$', 'post_add', name='blog_post_add'),
    url(r'^edit/(?P<id>\d+)/$', 'post_edit', name='blog_post_edit'),
    url(r'^delete/(?P<id>\d+)/$', 'post_delete', name='blog_post_delete'),
    url(r'^(?P<action>draft|public)/(?P<id>\d+)/$', 'post_change_status',
        name='blog_post_change_status'),
    url(r'^post/(?P<username>[\w\._\-]+)/(?P<slug>[-\w]+)/$',
        'user_post_detail', name='blog_user_post_detail')
)

if settings.ENABLE_USER_BLOG:
    urlpatterns += patterns('blog.views',
        url(r'^user/(?P<username>[\w\._\-]+)/$', 'user_post_list',
            {'compact_view': False}, name='blog_user_post_list'),
        url(r'^user/(?P<username>[\w\._\-]+)/compact/$', 'user_post_list',
            {'compact_view': True}, name='blog_user_post_compact_list'),
    )

if settings.ENABLE_BLOGS:
    urlpatterns += patterns('blog.views',
        url(r'^blogs/$', 'blog_list', name='blog_list'),
        url(r'^(?P<blog_slug>[-\w]+)/(?P<slug>[-\w]+)/$', 'post_detail', name='blog_post_detail'),
        url(r'^(?P<slug>[-\w]+)/$', 'blog_detail', name='blog_detail'),
    )

blog/models.py
# encoding: utf-8
from datetime import datetime
from pytils.translit import slugify

from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save, post_delete

if 'threadedcomments' in settings.INSTALLED_APPS:
    from threadedcomments.models import ThreadedComment
else:
    ThreadedComment = None

from tagging.fields import TagField

if 'voter' in settings.INSTALLED_APPS:
    from voter.models import RatingField

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class BlogUserAccess(models.Model):
    blog = models.ForeignKey('Blog', verbose_name=_("Blog"), 
        related_name="blog_user_access_list")
    user = models.ForeignKey(AUTH_USER_MODEL, verbose_name=_("User"),
        related_name="blog_user_access_list")
    is_moderator = models.BooleanField(_("Is moderator"), default=False)
    can_read = models.BooleanField(_("Can read"), default=False)
    can_write = models.BooleanField(_("Can write"), default=False)

class Blog(models.Model):
    name = models.CharField(_('Name'), max_length=200)
    slug = models.SlugField(_('Slug'))
    icon = models.ImageField(_('Blog icon'), height_field=None, width_field=None, blank=True, upload_to="blog_icons/", default="blog_icons/default.jpg")
    description = models.TextField(_('Description'), max_length=256, blank=True)

    user_access_list = models.ManyToManyField(AUTH_USER_MODEL, through=BlogUserAccess,
        related_name="blog_user_access_m2m_list", verbose_name=_("User access list"))
    can_read = models.BooleanField(_('Are everybody can read'), default=True)
    can_write = models.BooleanField(_('Are everybody can write'), default=True)

    class Meta:
        verbose_name = _('Blog')
        verbose_name_plural = _('Blogs')
    
    @models.permalink
    def get_absolute_url(self):
        return ('blog_detail', None, {
            'slug': self.slug
            })

    def __unicode__(self):
        return self.name

    def get_last_post(self):
        post = self.post_list.filter(status=Post.IS_PUBLIC)[:1]
        if post:
            return post[0]
        return None


class Post(models.Model):
    """Post model."""
    IS_DELETED = 0
    IS_DRAFT = 1
    IS_PUBLIC = 2

    STATUS_CHOICES = (
        (IS_DRAFT, _("Draft")), 
        (IS_PUBLIC, _("Public")),
        (IS_DELETED, _("Deleted"))
    )

    title = models.CharField(_("Title"), max_length=200)
    slug = models.SlugField(_("Slug"), blank=True)
    author = models.ForeignKey(AUTH_USER_MODEL, related_name='added_posts')
    creator_ip = models.CharField(_("IP Address of the Post Creator"),
        max_length=255, blank=True, null=True)
    tease = models.TextField(_("Tease"), blank=True)
    body = models.TextField(_("Body"))
    status = models.IntegerField(_("Status"), choices=STATUS_CHOICES, default=IS_DRAFT)
    allow_comments = models.BooleanField(_("Allow comments"), default=True)
    publish = models.DateTimeField(_("Publish"), default=datetime.now)
    created_at = models.DateTimeField(_("Created at"), default=datetime.now)
    updated_at = models.DateTimeField(_("Updated at"), default=datetime.now)
    tags = TagField()
    blog = models.ForeignKey(Blog, verbose_name=_("Blog"),
        related_name='post_list', null=True, blank=True)
    comments_count = models.IntegerField(_("Comments count"), default=0)
    last_comment_datetime = models.DateTimeField(_("Date of last comment"),
        default=datetime.now)
    
    if 'voter' in settings.INSTALLED_APPS:
        rating = RatingField(related_name="post_list")
        rating_score = models.FloatField(_("Rating score"), default=0)
    
    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ('-updated_at',)
        get_latest_by = 'updated_at'

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        if self.blog:
            return ('blog_post_detail', None, {
                'blog_slug': self.blog.slug,
                'slug': self.slug,
            })
        else:
            return ('blog_user_post_detail', None, {
                'username': self.author.username,
                'slug': self.slug,
            })

    def save(self, **kwargs):
        if (self.slug == None or self.slug == ''):
            if not self.id:
                super(Post, self).save(**kwargs)
            self.slug = ('%d-%s' % (self.id, slugify(self.title)))[:50]
        super(Post, self).save(**kwargs)

    @property
    def is_public(self):
        return self.status == self.IS_PUBLIC

    def is_visible_for_user(self, user):
        return self.is_public or self.author == user

    def comment_status_changed(self, comment, status):
        if not ThreadedComment:
            return
        if status == ThreadedComment.IS_PUBLIC:
            self.comments_count += 1
        elif status == ThreadedComment.IS_UNAPPROVED or status == ThreadedComment.IS_DELETED:
            self.comments_count -= 1
        self._feed_not_need_update = True
        self.save()
        self._feed_not_need_update = False

    def can_comment(self, user):
        return self.allow_comments

    def can_edit(self, user):
        return user.is_authenticated() and (self.author == user or \
            (self.blog and self.blog.blog_user_access_list.filter(user=user, is_moderator=True).exists()))

    def get_owners(self):
        return [self.author]

blog/templates/blog_jinja2/base.html
{% extends "site_base.html" %}

{% block extra_head %}
    <link href="{{ THEME_STATIC_URL }}css/blog.css" rel="stylesheet" type="text/css">
{% endblock %}

blog/templates/blog_jinja2/base_profile.html
{% extends "profile_base.html" %}

{% load i18n %}

{% block blog_tab_class %} ui-tabs-selected ui-state-active{% endblock %}

{% block right_block_outer %}{% endblock %}
{% block center_class%}full_width{% endblock %}
{% block body_content %}
    <div class="horizontal_filter">
        {% if request.user == current_user %}
            <a href="{% url blog_post_add %}" class="item{% block add_tab_class %}{% endblock %}">{% trans %}Write post{% endtrans %}</a>
        {% endif %}
        <a href="{% url blog_user_post_list current_user.username %}" class="item{% block post_list_tab_class %}{% endblock %}">{% trans %}Posts{% endtrans %}</a>
        <a href="{% url blog_user_post_compact_list current_user.username %}" class="item{% block post_compact_list_tab_class %}{% endblock %}">{% trans %}Posts (compact view){% endtrans %}</a>
    </div>
    {% block tab_content %}{% endblock %}
{% endblock %}

blog/templates/blog_jinja2/blog_detail.html
{% extends "blog/base.html" %}

{% load i18n %}
{% load misc_tags %}
{% load blog_tags %}
{% load feeds_tags %}

{% block head_title %}
    {% trans name=blog.name %}Posts in blog: {{ name }}{% endtrans %}
{% endblock %}

{% block extra_head %}
    {{ super() }}
    <link rel="alternate" type="application/atom+xml" title="{% trans name=blog.name %}Posts in blog: {{ name }}{% endtrans %}" href="/feeds/posts/blog/?slug={{ blog.slug }}" />
{% endblock %}

{% block bread_crumbs %}
    <a href="{% url "blog_list" %}">{% trans %}All blogs{% endtrans %}</a>
    <span class="tail"> » {% trans name=blog.name %}Blog: {{ name }}{% endtrans %}</span>
{% endblock %}
 
{% block body_inner %}
    <div id="right" class="info">
        <div class="inner">
            {% if blog.icon %}
                <img src="{{ blog.icon.url }}" width="140px"><br>
            {% endif %}
            <h2>{% trans name=blog.name %}Blog: {{ name }}{% endtrans %}</h2>
            {% if request.user.is_authenticated() %}
                <span class="actions">
                    {{ is_following(request.user, blog) }}
                    {% if following %}
                        <span><a href="{{ get_unfollow_url(blog) }}" rel="link" class="action">{% trans %}Unfollow{% endtrans %}</a></span>
                    {% else %}
                        <span><a href="{{ get_follow_url(blog) }}" rel="link" class="action">{% trans %}Follow{% endtrans %}</a></span>
                    {% endif %}
                </span>
            {% endif %}
            {% include "blog/tags.html" %}
        </div>
    </div>

    <div id="center">
        <div id="center_inner">
            {% set post_list = blog.post_list.all() %}
            {% if post_list.exists() %}
                <div class="blog_list" class="post_list">
                    {% include "blog/post_iterator.html" %}
                </div>
            {% else %}
                {% trans %}No posts yet.{% endtrans %}
            {% endif %}
        </div>
        <div class="clearfix"></div>
    </div>
{% endblock %}

blog/templates/blog_jinja2/blog_list.html
{#% extends "blog/base.html" %#}
{% extends "search/all.html" %}

{% from "pagination/jinja2_pagination.html" import paginate %}
{% from "containers/_username.html" import render_username %}

{% block head_title %}{% trans %}All blogs{% endtrans %}{% endblock %}

{% block extra_head %}
    {{ super() }}
    <link href="{{ THEME_STATIC_URL }}css/blog.css" rel="stylesheet" type="text/css">    
{% endblock %}

{% block body %}
    <h1>{% trans %}All blogs{% endtrans %}</h1>
    
    <table class="all_blogs">
        <thead>
            <tr><th class="blog_icon_column"></th><th>{% trans %}Blog name{% endtrans %}</th><th class="column-center" style="text-align: center;">{% trans %}Posts count{% endtrans %}</th><th>{% trans %}Last post{% endtrans %}</th></tr>
        </thead>
        <tbody>
        {% autopaginate blog_list %}
        {% if blog_list %}
            {% for blog in blog_list %}
                <tr class="{{ loop.cycle("odd", "even") }}">
                    <td class="column-center blog_icon_column">
                        {% if blog.icon %}
                            <img src="{{ blog.icon.url }}" class="blog_icon">
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ blog.get_absolute_url() }}">{{ blog.name }}</a><br/>
                        {{ blog.description }}
                    </td>
                    <td class="column-center">
                        {{ blog.post_list.count() }}
                    </td>
                    <td>
                        {% set post_list = blog.post_list.filter(status=2) %}
                        {% if post_list %}
                            {% set post = post_list.0 %}
                            {{ render_username(request, post.author) }}
                            <p><a href="{{ post.get_absolute_url() }}" class="post_link">{{ post.title }}</a></p>
                            <span class="timestamp" title="{{ post.updated_at }}">{% trans time=post.updated_at|timesince() %}{{ time }} ago{% endtrans %}</span>
                        {% else %}
                            {% trans %}No posts yet.{% endtrans %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            {% trans %}No blogs found.{% endtrans %}
        {% endif %}
        {{ paginate(blog_list_pages) }}
        </tbody>
    </table>
{% endblock %}

blog/templates/blog_jinja2/post_compact_iterator.html
{% load i18n %}

{% for post_list_by_status in post_list|groupby('status') %}
    <h2>{{ post_list_by_status.list.0.get_status_display() }}</h2>
    <table class="post_compact_list">
        <thead>
            <td>{% trans %}Title{% endtrans %}</td>
            <td>{% trans %}Created{% endtrans %}</td>
            <td>{% trans %}Updated{% endtrans %}</td>
            <td>{% trans %}Actions{% endtrans %}</td>
        </thead>
        {% for post in post_list_by_status.list %}
            <tr>
                <td>
                    {% if post.blog %}
                        <a href="{{ post.blog.get_absolute_url() }}" class="blog_link_small">{{ post.blog.name }}</a>
                        <span class="blog_post_breaker_small">&rarr;</span>
                    {% endif %}
                    <a href="{{ post.get_absolute_url() }}" class="post_link_small">{{ post.title }}</a>
                </td>
                <td class="date">{{ post.created_at|date("d M Y, H:i") }}</td>
                <td class="date">{{ post.updated_at|date("d M Y, H:i") }}</td>
                {% if request.user == current_user or request.user.is_superuser %}
                    <td class="actions">
                        <ul>
                            <li><a href="{% url "blog_post_edit" post.id %}" class="inline_action">{% trans %}Edit{% endtrans %}</a></li>
                            {% if post.is_public %}
                                <li><a href="{% url "blog_post_change_status" 'draft', post.id %}" class="inline_action">{% trans %}To drafts{% endtrans %}</a></li>
                            {% else %}
                                <li><a href="{% url "blog_post_change_status" 'public', post.id %}" class="inline_action">{% trans %}Publish{% endtrans %}</a></li>
                                <li><a href="{% url "blog_post_delete" post.id %}" class="inline_action">{% trans %}Delete{% endtrans %}</a></li>
                            {% endif %}
                        </ul>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endfor %}

blog/templates/blog_jinja2/post_edit.html
{% extends "blog/base.html" %}

{% load i18n %}
{% load uni_form_tags %}

{% block head_title %}{% trans %}Editing the post{% endtrans %}{% endblock %}

{% block external_css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ STATIC_URL }}redactor/css/redactor.css">
{% endblock %}

{% block extra_head %}
    <link href="{{ THEME_STATIC_URL }}css/blog.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block external_js %}
    {{ super() }}
    <script src="{{ STATIC_URL }}redactor/redactor.js"></script>
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="{{ STATIC_URL }}js/blog.js"></script>
{% endblock %}

{% block inline_js %}
$(function() { $('#id_blog').chosen(); });
{% endblock %}

{% block body %}
    <h1>{% trans %}Editing the post{% endtrans %}</h1>
    <form class="uniForm" id="edit_post_form" method="POST" action="{% url blog_post_edit post.id %}">
        {% csrf_token %}
        <fieldset class="inlineLabels">
            {{ post_form|as_uni_form }}
            <input type="submit" class="submit default" value="{% trans %}Update{% endtrans %}"/>
        </fieldset>
    </form>
{% endblock %}

blog/templates/blog_jinja2/post_item.html
{% from "auth/profile_bubblepopup.html" import get_profile_bubblepopup %}
{% from "voter/default_rating.html" import render_rating %}

{% macro _show_blog_post(post, post_undetailed) -%}
    {% if post.is_visible_for_user(request.user) %}
        <div class="blog_post clearfix">
            <div class="blog_post_title">
                {% if post.blog %}  
                    <a href="{{ post.blog.get_absolute_url() }}" class="blog_link">{{ post.blog.name }}</a>
                    <span class="blog_post_breaker">&rarr;</span>
                {% endif %}
                <a href="{{ post.get_absolute_url() }}" class="post_link"><h1>{{ post.title }}</h1></a>
                {% if post.can_edit(request.user) %}
                    <a href="{% url "blog_post_edit" post.id %}" class="icon_edit"><img src="{{ THEME_STATIC_URL }}img/icons/edit.png" alt="{% trans %}Edit{% endtrans %}"></a>
                    {% if post.is_public %}
                        <b>{% trans %}Draft{% endtrans %}</b>
                        [ <a href="{% url "blog_post_change_status" 'public', post.id %}" class="inline_action">{% trans %}Publish{% endtrans %}</a> ]
                        [ <a href="{% url "blog_post_delete" post.id %}" class="inline_action">{% trans %}Delete{% endtrans %}</a> ]
                    {% else %}
                        [ <a href="{% url "blog_post_change_status" 'draft', post.id %}" class="inline_action">{% trans %}To drafts{% endtrans %}</a> ]
                    {% endif %}
                {% endif %}
            </div>
            <div class="blog_post_tease">
                {% if post_undetailed and post.tease %}
                    {{ post.tease|safe() }}
                {% else %}
                    {{ post.body|safe() }}
                {% endif %}
            </div>
            <div class="clearfix"></div>
            <div class="blog_post_meta">
                <div class="avatarname">
                    <span class="with_popup">
                        <a class="username" href="{% url "poetry_user_works" post.author.username %}">
                            {{ avatar(post.author, 20) }} {{ post.author.username }}
                            <span class="fullname">{{ post.author.get_profile().display_name }}</span>
                        </a>
                        {{ get_profile_bubblepopup(request, post.author) }}
                    </span>
                </div>
                <div class="blog_post_date">
                    {{ post.updated_at|date("d M Y, H:i") }}
                    {% if post.allow_comments %}
                        | <a href="{{ post.get_absolute_url() }}">
                            {% trans comments_count=post.comments_count %}Comments: {{ comments_count }}{% endtrans %}
                        </a>
                    {% endif %}
                    |
                </div>
                {{ share_it(request, post.get_absolute_url(), post.title) }}
                {{ render_rating(request.user, post, "post", post.author) }}
                <div class="clearfix"></div>
            </div>
        </div>
        {{ share_js(request) }}
    {% endif %}
{%- endmacro %}

{% macro show_blog_post(post) -%}
    {{ _show_blog_post(post, true) }}
{%- endmacro %}

{% macro show_full_blog_post(post) -%}
    {{ _show_blog_post(post, false) }}
{%- endmacro %}

blog/templates/blog_jinja2/post_iterator.html
{% from "pagination/jinja2_pagination.html" import paginate %}
{% from "blog/post_item.html" import show_blog_post with context %}

{% autopaginate post_list %}

{% for post in post_list %}
    {{ show_blog_post(post) }}
{% endfor %}

{{ paginate(post_list_pages) }}

blog/templates/blog_jinja2/post_list.html
{#% extends "blog/base.html" %#}
{% extends "search/all.html" %}

{% load i18n %}

{% block head_title %}{% trans %}All posts{% endtrans %}{% endblock %}
{% block seo_keywords %}{% trans %}All posts{% endtrans %}{% endblock %}
{% block seo_description %}{% trans %}All posts{% endtrans %}. {{ super() }}{% endblock %}

{% block extra_head %}
    {{ super() }}
    <link href="{{ THEME_STATIC_URL }}css/blog.css" rel="stylesheet" type="text/css">    
    <link rel="alternate" type="application/atom+xml" title="{% trans %}All posts{% endtrans %}" href="/feeds/posts/all/" />
{% endblock %}

{% block body %}
    <h1>{% trans %}All posts{% endtrans %}</h1>
    {% if post_list %}
        {% include "blog/post_iterator.html" %}
    {% else %}
        {% trans %}No posts yet.{% endtrans %}
    {% endif %}
{% endblock %}

blog/templates/blog_jinja2/tags.html
{#{% comment %} Not need now.
{% load tagging_tags %}

{% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}

<div class="tag_cloud">
    {% for tag in tags %}
        <a href="{% url tag_results tag.name %}"><span class="cloud_{{ tag.font_size }}">{{ tag.name }}</span></a>
    {% endfor %}
</div>
{% endcomment %}#}

blog/templates/blog_jinja2/user_post_base_list.html
{% extends "blog/base_profile.html" %}

{% load i18n %}

{% block head_title %}{{ current_user.get_profile().display_name }} - {% trans %}Posts{% endtrans %}{% endblock %}
{% block seo_keywords %}{% trans %}Posts{% endtrans %}, {{ current_user.get_profile().display_name }}, {% for post in post_list[:3] %}{{ post.title }}, {% endfor %}{% trans %}Blogs{% endtrans %}{% endblock %}
{% block seo_description %}{{ current_user.get_profile().display_name }}, {% trans %}Posts{% endtrans %}:{% for post in post_list[:3] %} {{ post.title }}.{% endfor %}.. {{ super() }}{% endblock%}

{% block external_css %}
    {{ super() }}
    <link rel="alternate" type="application/atom+xml" title="{% trans name=current_user.name %}Blog post feed for user {{ name }}{% endtrans %}" href="/feeds/posts/only/?username={{ current_user.username }}" />
{% endblock %}

{% block extra_head %}
    <link href="{{ THEME_STATIC_URL }}css/blog.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block bread_crumbs %}
    {{ super() }}
    <span class="tail"> » {% trans %}Blog{% endtrans %}</span>
{% endblock %}

blog/templates/blog_jinja2/user_post_compact_list.html
{% extends "blog/user_post_base_list.html" %}

{% load i18n %}

{% block post_compact_list_tab_class %} selected{% endblock %}

{% block tab_content %}
    {% if post_list %}
        {% include "blog/post_compact_iterator.html" %}
    {% else %}
        <h2>{% trans %}No posts yet.{% endtrans %}</h2>
    {% endif %}
{% endblock %}

blog/templates/blog_jinja2/user_post_full_list.html
{% extends "blog/user_post_base_list.html" %}

{% load i18n %}

{% block post_list_tab_class %} selected{% endblock %}

{% block tab_content %}
    {% if post_list %}
        {% include "blog/post_iterator.html" %}
    {% else %}
        <h2>{% trans %}No posts yet.{% endtrans %}</h2>
    {% endif %}
{% endblock %}

blog/templates/blog_jinja2/user_post_list.html
{% if compact_view %}
    {% include "blog/user_post_compact_list.html" %}
{% else %}
    {% include "blog/user_post_full_list.html" %}
{% endif %}